config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get ":user_id/edit", to: "profiles#edit", as: :edit_profile
  patch ":user_id/edit", to: "profiles#update", as: :update_profile

  resources :bookings
  get "bookings/:id/edit_cancel" => "bookings#edit_cancel", as: :edit_cancel
  post "/bookings/cancel" => "bookings#cancel"

  namespace :admin do
    resources :users, only: [:edit, :update, :index]
    resources :bookings
    post "/bookings/:id" => "bookings#cancel_booking"
    post "/deactivate", to: "users#deactivate"
    post "/activate", to: "users#activate"
  end
  root "bookings#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  self.per_page = 10

  validates :seat, presence: true
  validates :start_date, presence: true
  validates :expiration_date, presence: :true
  validate :start_date_cannot_be_in_the_past,:expiration_date_cannot_be_in_the_past,
  :expiration_date_cannot_be_less_than_start_date, :desk_alreay_taken

  # custom validation for booking desk

  def start_date_cannot_be_in_the_past
    errors.add(:start_date, 'can not be in past') if start_date.present? && start_date < Date.today
  end

  def expiration_date_cannot_be_in_the_past
    errors.add(:expiration_date, 'can not be in past') if expiration_date.present? && expiration_date < Date.today
  end

  def expiration_date_cannot_be_less_than_start_date
    errors.add(:start_date, 'can not be greater than expiration date') if start_date.present? && expiration_date.present? && expiration_date < start_date
  end

  def desk_alreay_taken
    bookings = Booking.where(seat: self.seat, start_date: self.start_date..self.expiration_date)
    errors.add(:seat, 'aleardy booked for given dates') if bookings.count > 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :bookings

  def active_for_authentication?
    super and self.active?
  end

  def activate_account!
    update_attribute :active, true
    binding.pry
  end

  def deactivate_account!
    update_attribute :active, false
    binding.pry
  end
end

app/controllers/admin/bookings_controller.rb
class Admin::BookingsController < ApplicationController
  before_action :redirect_unless_admin!

  def show
    @booking = Booking.find(params[:id])
  end

  def index
    @bookings = Booking.all.paginate(:page => params[:page]).order('id DESC')
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    binding.pry
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    @booking.status = "Booked"
    if @booking.save
      flash[:success] = "seat added!"
      redirect_to bookings_path
    else
      render :new
     end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
     @booking = Booking.find(params[:id])
     if @booking.update(booking_params)
      flash[:success] = "Desk updated!"
      redirect_to bookings_path
    else
      render :edit
     end
  end


  def thank_you
    @tour = Booking.find(params[:tour_id])
    @booking = Booking.last
  end

  def cancel_booking
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      @booking.status = "Canceled"
      flash[:success] = "Desk updated!"
      redirect_to bookings_path
    else
      render :edit
     end
  end

  private

  def booking_params
    params.require(:booking).permit(:seat, :start_date, :expiration_date)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!, :redirect_unless_admin!

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def deactivate
    binding.pry
    user = User.find(params[:user_id])
    if current_user.is_admin?
      user.deactivate_account!
      redirect_to admin_users_path
    else
      redirect_to :back
    end
  end

  def activate
    binding.pry
    user = User.find(params[:user_id])
    if current_user.is_admin?
      user.activate_account!
      redirect_to admin_users_path
    else
      redirect_to :back
    end
  end

  def update
    binding.pry
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    if @user.update(user_params)
      flash[:notice] = "Successfully updated User."
      redirect_to admin_users_path
    else
      render :action => 'edit'
    end
  end

  private

  def user_params
     params.require(:user).permit(:active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: false
  before_action :configure_permitted_parameters, if: :devise_controller?


  helper_method :resource_name, :resource, :devise_mapping

  def after_sign_in_path_for(_resource)
    if current_user && current_user.is_admin == true
      admin_bookings_path
    else
      bookings_path
    end
  end

  def view_cancel_booking_link?
    true if current_user.try(:is_admin?)
  end

  def redirect_unless_admin!
    unless current_user.try(:is_admin?)
      binding.pry
      flash[:error] = "You are not authorized to access this page!"
      redirect_to root_path
    end
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    update_attrs = %i[password password_confirmation current_password]
    devise_parameter_sanitizer.permit :account_update, keys: update_attrs
    devise_parameter_sanitizer.permit(:sign_in) {|u| u.permit(:email, :password, :remember_me)}
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_booking, only: [:show, :edit, :update, :edit_cancel]
  before_action :authenticate_user!

  def show; end

  def index
    @bookings = Booking.all.paginate(:page => params[:page]).order('id DESC')
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    @booking.status = "active"
    if @booking.save
      flash[:success] = "Desk added!"
      redirect_to bookings_path
    else
      render :new
     end
  end

  def edit; end

  def update
     @booking = Booking.find(params[:id])
     if @booking.update(booking_params)
      flash[:success] = "Desk updated!"
      redirect_to bookings_path
    else
      render :edit
     end
  end


  def thank_you
    @tour = Booking.find(params[:booking_id])
    @booking = Booking.last
  end

  def set_booking
   @booking = Booking.find(params[:id])
  end

  def edit_cancel; end

  def cancel
    binding.pry
    @booking = Booking.find(params[:booking][:id])
    @booking.cancellation_reason = params[:booking][:cancellation_reason]
    @booking.cancellation_comment =params[:booking][:cancellation_comment]
    @booking.status = "Canceled"
    if @booking.save(:validate => false)
      flash[:success] = "Desk cancelled!"
      redirect_to bookings_path
    else
      render :edit
     end
  end


  private

  def booking_params
    params.require(:booking).permit(:seat, :start_date, :expiration_date)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update show]
  before_action :authenticate_user!

  def edit
    @user = User.find_by(id: params[:user_id])
  end

  def update
    if @user.update(profile_params)
      flash[:success] = "Your profile updated"
      redirect_to edit_profile_path(@user.id)
    else
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  def set_user
    @user = User.find_by(id: params[:user_id])
  end

  def profile_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/bookings/cancel_booking.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-3 offset-sm-3 col-xs-12 back-ground user-forms">
      <% if action_name == "new" %>
      <h3 class="text-center header_color">New desk</h3>
      <% else %>
      <h3 class="text-center header_color">Edit desk</h3>
      <% end %>
      <%= form_for (@booking, url: admin_bookings_cancel_path)  do |f| %>
         <% if @booking.errors.any? %>
            <div id="error_explanation">
              <h4><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being
                saved:</h4>
              <ul>
                <% @booking.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        <div class="form-group">
          <%= f.label :seat %>
        </div>
        <div class="form-group">
          <%= f.label :cancellation_reason %>
          <%= f.text_field :cancellation_reason, :class => 'form-control'%>
        </div>
        <div class="form-group">
          <%= f.label :cancellation_comment %>
          <%= f.text_field :cancellation_comment, :class => 'form-control'%>
        </div>
        <div class="form-group">
          <%= submit_tag("Cancel", :class => "btn btn-success form-control", :name => "submit") %>
          </div>

          <%= link_to "Back", bookings_path %>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('.pickadate').pickadate();
  });
</script>

</script>

app/views/admin/bookings/index.html.erb
<h3 class="text-center header_color header-top">Bookings</h3>
<div class="data_table_res container">
  <%= link_to "Add desk", new_booking_path, :class => "pull-right" %>
  <table class="table table-bordered dttb">
    <thead>
    <tr class="table-heading">
      <th class="text-center">Name</th>
      <th class="text-center">Desk</th>
      <th class="text-center">From/To</th>
      <th class="text-center">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @bookings.each do |booking_detail| %>
      <tr class="text-center">
        <td><%= booking_detail.user.name %></td>
        <td><%= booking_detail.seat %></td>
        <td><%= booking_detail.start_date.strftime("%B %d") if booking_detail.start_date %>--<%= booking_detail.expiration_date.strftime("%B %d") if booking_detail.expiration_date %> </td>
        <td class="text-center">
          <% if booking_detail.expiration_date >= Date.today %>
            <%= link_to "Cancel", edit_admin_booking_path(booking_detail.id), class: "", style: "margin-left:5px" %>
            <%= link_to "View", booking_path(booking_detail.id), class: "", style: "margin-left:5px" %>
            <%= link_to "Edit", edit_booking_path(booking_detail.id), class: "", style: "margin-left:5px" %>
            <% else %>
             <%= link_to "Past", "", class: "", style: "margin-left:5px" %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= will_paginate @bookings, :class => "pull-right" %>
</div>

app/views/admin/users/edit.html.erb
<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="profile">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12 back-ground user-forms">
      <h3 class="text-center header_color">Activate/Deactive User</h3>
      <%= form_for @user, url: admin_user_path do |f| %>
        <div class="form-group">
          <%= f.label :active %>
          <%= f.check_box :active %>
        </div>
        <div class="form-actions">
         <%= submit_tag("Deactive", :class => "btn btn-success form-control", :name => "submit") %>
        </div>
      <% end %>
      <%= link_to "Back", :back %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<h3 class="text-center header_color header-top">Users</h3>
<div class="data_table_res container">
   <table id="product_lists" class="table table-bordered dttb">
    <thead>
    <tr class="table-heading">
      <th class="text-center"> Name</th>
      <th class="text-center">Email</th>
      <th class="text-center">Active</th>
     <th class="text-center">Actions</th>

    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr class="text-center">
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.active %></td>
        <td><%= link_to "View", admin_user_path(user.id), class: "", style: "margin-left:5px" %>
        <% if current_user.is_admin? && user != current_user && user.active %> <%=link_to "Deactivate", admin_deactivate_path(user_id: user), method: :post, data: { confirm: "Are you sure?" } %> <% end %>

        <% if current_user.is_admin? && user != current_user && !user.active %> <%=link_to "Activate", admin_activate_path(user_id: user), method: :post, data: { confirm: "Are you sure?" } %> <% end %>

        <%#= link_to user.active ? "Deactivate User" : "Activate User", edit_admin_user_path(user.id), class: "btn btn-primary btn-xs", style: "margin-left:5px" %>
        </td>

      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<script type="text/javascript">
  $(document).ready(function () {
    $("#product_lists").DataTable();
    true
  });
</script>

app/views/bookings/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-3 offset-sm-3 col-xs-12 back-ground user-forms">
      <% if action_name == "new" %>
      <h3 class="text-center header_color">New desk</h3>
      <% else %>
      <h3 class="text-center header_color">Edit desk</h3>
      <% end %>
      <%= form_for (@booking)  do |f| %>
         <% if @booking.errors.any? %>
            <div id="error_explanation">
              <h4><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being
                saved:</h4>
              <ul>
                <% @booking.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        <div class="form-group">
          <%= f.label :choose_seat %>
          <%= f.text_field :seat, :autofocus => true, :class => 'form-control'%>
        </div>
        <div class="form-group">
          <%= f.label :start_date %>
          <%= f.text_field :start_date, :class => 'form-control pickadate'%>
        </div>
        <div class="form-group">
          <%= f.label :end_date %>
          <%= f.text_field :expiration_date, :class => 'form-control pickadate'%>
        </div>
        <div class="form-group">
          <%= submit_tag("Submit", :class => "btn btn-success form-control", :name => "submit") %>
          </div>

          <%= link_to "Back", bookings_path %>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('.pickadate').pickadate();
  });
</script>

</script>

app/views/bookings/edit.html.erb
<%= render 'form' %>

app/views/bookings/edit_cancel.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-3 offset-sm-3 col-xs-12 back-ground user-forms">
      <% if action_name == "new" %>
      <h3 class="text-center header_color">New desk</h3>
      <% else %>
      <h3 class="text-center header_color">Edit desk</h3>
      <% end %>
      <%= form_for @booking, :url => {:controller => "/bookings", :action => "cancel"}, html: {method: :post }  do |f| %>
        <%=f.hidden_field :id,:value=> f.object.id%>
        <div class="form-group">
          <%= f.label :cancellation_reason %>
          <%= f.text_field :cancellation_reason, :class => 'form-control'%>
        </div>

        <div class="form-group">
          <%= f.label :cancellation_comment %>
          <%= f.text_field :cancellation_comment, :class => 'form-control'%>
        </div>

        <div class="form-group">
          <%= submit_tag("Cancel", :class => "btn btn-success form-control", :name => "submit") %>
        </div>

        <%= link_to "Back", bookings_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<h3 class="text-center header_color header-top">Bookings</h3>
<div class="data_table_res container">
  <%= link_to "Add desk", new_booking_path, :class => "pull-right" %>
  <table class="table table-bordered dttb">
    <thead>
    <tr class="table-heading">
      <th class="text-center">Name</th>
      <th class="text-center">Desk</th>
      <th class="text-center">Status</th>
      <th class="text-center">From/To</th>
      <th class="text-center">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @bookings.each do |booking_detail| %>
      <tr class="text-center">
        <td><%= booking_detail.user.name %></td>
        <td><%= booking_detail.seat %></td>
        <td><%= booking_detail.status %></td>
        <td><%= booking_detail.start_date.strftime("%B %d") if booking_detail.start_date %>--<%= booking_detail.expiration_date.strftime("%B %d") if booking_detail.expiration_date %> </td>
        <td class="text-center">
          <%= link_to "View", booking_path(booking_detail.id), class: "", style: "margin-left:5px" %>
          <% if booking_detail.expiration_date >=  Date.today %>
            <%= link_to "Edit", edit_booking_path(booking_detail.id), class: "", style: "margin-left:5px" %>
            <%= link_to "Cancel", edit_cancel_path(booking_detail.id), class: "", style: "margin-left:5px" %>
            <% else %>
             <%= link_to "Past", "", class: "", style: "margin-left:5px" %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= will_paginate @bookings, :class => "pull-right" %>
</div>

app/views/bookings/new.html.erb
<%= render 'form' %>

app/views/bookings/show.html.erb
<h3 class="text-center header_color">Booking Details</h3>
<div class="container">
  <table class="table table-bordered">
   <thead>
    <tr>
      <th class="text-center">Name</th>
      <th class="text-center">Desk</th>
      <th class="text-center">Booking from</th>
      <th class="text-center">Booking till</th>
      <th class="text-center">Action</th>
    </tr>
    </thead>
    <tbody>
      <tr class="text-center">
        <td><%= @booking.seat %></td>
        <td><%= @booking.user.name %></td>
        <td><%= @booking.seat %></td>
        <td><%= @booking.start_date.strftime("%d") %>--<%= @booking.expiration_date.strftime("%B %d") %> </td>
        <td><a href="javascript:history.back()">back</a></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/bookings/thank_you.html.erb
<div class="container"></br>
  <div class="thank_you">
    <h2 class="text-center"> Thank you <span><%= current_user.name if current_user %> </span>for booking with us.</h2>
    <div class="row">
      <h3>Confimed Booking Details</h3></br>
      <div class="col-lg-5">
        <p><span><strong>Tour Name: </strong></span><span><%= @tour.tour_name %></span></p>
        <p><span><strong>Booking Date: </strong></span><span><%= Date.today.strftime("%B %d, %Y") %></span></p>
        <p><span><strong>Journey Date: </strong></span><span><%= @booking.tour_date.strftime("%B %d, %Y") %></span></p>
        <p><span><strong>Duration: </strong></span><span><%= @tour.duration %></span></p>
        <p><span><strong>Route: </strong></span><span><%= @tour.route %></span></p>
      </div>
      <div class="col-lg-4">
        <p><span><strong>No of Passenger: </strong></span><span><%= @booking.customer_count %></span></p>
        <p><span><strong> Total amount: </strong></span><span>$<%= @booking.booking_amount %></span></p>
        <p><span><strong> Amount paid: </strong></span><span>$<%= 25 %></span></p>
        <p><span><strong>Site: </strong></span><span><%= @tour.site %></span></p>
      </div>
      <div class="col-lg-3">
        <%= image_tag @tour.avatar.thumb.to_s, :alt => "tour", :width => "100%", :height => "165px", :class => "pull-right" %>
      </div>
    </div>
    </br>
    <p class="text-center" style="font-size: 21px">Your booking is completed. We will send you email with link for
      payment.</p>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="container alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand logo" href="/" >hotdesk</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="">
        <ul class="nav navbar-nav navbar-right header-list-font-familty">
          <% if user_signed_in? %>
            <li class="list-dropdown"><%= link_to "Bookings", admin_bookings_path %>
            <li class="list-dropdown"><%= link_to "Users", admin_users_path %>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %>
                <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "View Profile", edit_profile_path(current_user.id) %></li>
                <li><%= link_to "Change your password", edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li class="list-dropdown">
              <a href="/users/sign_in">
                <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>Log in</a>
            </li>
            <li class="list-dropdown">
              <a href="/users/sign_up">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Sign up </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotDeskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/navbar'%>
  <%= render 'layouts/messages' %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="user_forms">
    <ul class="nav nav-tabs text-center" role="tablist">
      <li role="presentation" class="active">
        <a href="#profile" aria-controls="home" role="tab" data-toggle="tab">Profile</a></li>
      <li role="presentation"><%= link_to "Change  Password", edit_user_registration_path %></li>
    </ul>
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="profile">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12 set_priority_edit">
            <h3 class="text-center">Staff Details</h3></br>
            <%= form_for @user, url: {action: "update"}, html: {multipart: true} do |f| %>
              <div class="form-group required">
                <label for="firstname" class="control-label "> Name:</label>
                <%= f.text_field :name, :class => 'form-control' %>
              </div>

              <div class="form-group required">
                <label for="email" class="control-label ">Email:</label>
                <%= f.text_field :email, :class => 'form-control' %>
              </div>

              <div class="form-group required">
                <label for="phno" class="control-label ">Fields required for booking</label>
              </div>

              <div class="form-group">
                <%= f.submit "Update", :class => "btn btn-success form-control" %>
              </div>
            <% end %>
            <hr>
          </div>
        </div>
      </div>
    </div>
  </div>


<script type="text/javascript">
  $(document).ready(function () {
    var today = new Date();
    $('#datetimepicker').datetimepicker({
      format: 'DD/MM/YYYY',
      maxDate: today
    });
  });
</script>